apps/run_web/lib/run_web/router.ex
defmodule RunWeb.Router do
  use RunWeb, :router

  import RunWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RunWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RunWeb.Page do
    pipe_through :browser

    get "/", LandingController, :index, as: :landing_page
    get "/about", AboutController, :index, as: :about_page
    get "/sign-up", SignUpController, :index, as: :sign_up_page
    get "/training", TrainingController, :index, as: :training_page
    get "/contact", ContactController, :index, as: :contact_page
    get "/calendar", CalendarController, :index, as: :calendar_page
    get "/events", EventsController, :index, as: :events_page
    get "/committees", CommitteesController, :index, as: :committees_page
  end

  # Other scopes may use custom stacks.
  # scope "/api", RunWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: RunWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", RunWeb.User do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", RegistrationController, :new, as: :user_registration
    post "/users/register", RegistrationController, :create, as: :user_registration
    get "/users/log_in", SessionController, :new, as: :user_session, as: :user_session
    post "/users/log_in", SessionController, :create, as: :user_session
    get "/users/reset_password", ResetPasswordController, :new, as: :user_reset_password
    post "/users/reset_password", ResetPasswordController, :create, as: :user_reset_password
    get "/users/reset_password/:token", ResetPasswordController, :edit, as: :user_reset_password
    put "/users/reset_password/:token", ResetPasswordController, :update, as: :user_reset_password
  end

  scope "/users", RunWeb.User do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings/confirm_email/:token", SettingsController, :confirm_email,
      as: :user_settings
  end

  scope "/user", RunWeb.User do
    pipe_through [:browser, :require_authenticated_user]

    # get "", UserController, :show

    get "/settings", SettingsController, :edit, as: :user_settings
    put "/settings", SettingsController, :update, as: :user_settings

    get "/password", PasswordController, :edit, as: :password
    put "/password", PasswordController, :update, as: :password
  end

  scope "/", RunWeb.User do
    pipe_through [:browser]

    delete "/users/log_out", SessionController, :delete, as: :user_session
    get "/users/confirm", ConfirmationController, :new, as: :user_confirmation
    post "/users/confirm", ConfirmationController, :create, as: :user_confirmation
    get "/users/confirm/:token", ConfirmationController, :edit, as: :user_confirmation
    post "/users/confirm/:token", ConfirmationController, :update, as: :user_confirmation
  end

  scope "/admin", RunWeb.Admin do
    pipe_through [:browser, :require_admin]
    get "/", DashboardController, :index, as: :admin

    resources "/blogs", BlogController, as: :admin_blogs, only: [:index, :show, :edit, :update] do
      resources "/posts", PostController
    end

    resources "/users", UsersController, as: :admin_users do
      resources "/memberships", MembershipController
    end
  end

  scope "/admin", RunWeb.Admin do
    pipe_through [:browser, :require_admin, :require_architect]
    resources "/blog", BlogController, as: :admin_blog, only: [:new, :create, :delete]

    resources "/committees", CommitteeController, as: :admin_committee do
      resources "/members", CommitteeMemberController, except: [:index, :show], as: :member
      resources "/meetings", CommitteeMeetingController, except: [:index, :show], as: :meeting
    end
  end

  scope "/club", RunWeb.Club do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/member/new", MemberController, :new, as: :new_member
    post "/member", MemberController, :create, as: :new_member
  end

  scope "/club", RunWeb.Club do
    pipe_through [:browser, :require_authenticated_user]

    get "/membership", MembershipController, :new, as: :new_membership
    post "/membership", MembershipController, :create, as: :new_membership

    get "/membership/:id/success", PaymentSuccessController, :show,
      as: :membership_payment_success

    get "/membership/:id/error", PaymentErrorController, :show, as: :membership_payment_error
    get "/invoice/:id", InvoiceController, :show
  end

  scope "/member", RunWeb.Club do
    pipe_through [:browser, :require_authenticated_user]

    get "/edit", MemberController, :edit, as: :edit_member
    get "/", MemberController, :show, as: :show_member
    put "/", MemberController, :update, as: :update_member
  end

  scope "/committee", RunWeb.Committee do
    pipe_through [:browser, :require_authenticated_user]

    resources "/", CommitteeController do
      get "/meetings", MeetingController, as: :admin_committee_meeting
      resources "/messages", MessageController, except: [:edit, :update, :delete]
    end
  end

  scope "/payment", RunWeb.Payment do
    pipe_through [:browser, :require_authenticated_user]

    get "/checkout", CheckoutController, :new, as: :checkout
    get "/completed", CompletedController, :show, as: :payment_completed
    get "/error", ErrorController, :show, as: :payment_error
  end

  scope "/super", RunWeb.Super do
    pipe_through [:browser, :require_super]
    get "/", DashboardController, :index, as: :super_dashboard

    resources "/users", UserController, as: :super_users
  end
end

apps/run_web/lib/run_web/views/layout_view.ex
defmodule RunWeb.LayoutView do
  use RunWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

apps/run_web/lib/run_web/templates/layout/_breadcrumbs.html.heex
<%= if @breadcrumbs.show do %>
<nav class="
  z-10 
  flex 
  items-center 
  justify-between 
  flex-wrap 
  bg-gray-100 
  p-2 
  fixed 
  w-full 
  h-12 
  top-20">
  <div class="md:container md:mx-auto">
    <ol class="list-reset flex">
      <li>
        <%= live_patch @breadcrumbs.root.title, to: @breadcrumbs.root.path, class:  "text-blue-600 hover:text-blue-700"%>
        <%= for breadcrumb <- @breadcrumbs.links do %>
          <li><span class="text-gray-500 mx-2">/</span></li>
          <%= link breadcrumb.title, to: breadcrumb.path, class: "text-blue-600 hover:text-blue-700" %>
        <% end %>
        <li><span class="text-gray-500 mx-2">/ <%= @breadcrumbs.current_page %></span></li>
      </li>
    </ol>
  </div>
</nav>
<% end %>

apps/run_web/lib/run_web/templates/layout/_footer.html.heex
<footer class="p-4 md:px-6 md:py-8 bg-gray-900 site-footer">
  <div class="sm:flex sm:items-center sm:justify-between">
      <a href="https://flowbite.com/" class="flex items-center mb-4 sm:mb-0">
          <img src={Routes.static_path(@conn, "/images/lif-logo.svg")} class="mr-3 h-8" alt="LIF Logo">
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">LIF Løb og Motion</span>
      </a>
      <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
          <li>
              <a href="#" class="mr-4 hover:underline md:mr-6 ">About</a>
          </li>
          <li>
              <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
          </li>
          <li>
              <a href="#" class="mr-4 hover:underline md:mr-6 ">Ingen cookies</a>
          </li>
          <li>
              <a href="#" class="hover:underline">Contact</a>
          </li>
      </ul>
  </div>
  <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8">
  <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400"><%= gettext("This project is open source:") %> 
  <a href="https://github.com/maxgronlund/lif-lm/" class="hover:underline"><%= gettext("Find the code at github")%></a>
  </span>
</footer>

apps/run_web/lib/run_web/templates/layout/_navbar.html.heex
<nav class="fixed w-full top-0 pt-4 px-2 sm:px-4 py-2.5 bg-red-600 h-20 z-40">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link to: Routes.landing_page_path(@conn, :index), class: "flex items-center" do%>
        <img src={Routes.static_path(@conn, "/images/lif-logo.svg")} class="mr-3 h-12" alt="LIF Logo">
        <span class="hidden lg:block  sm:self-center text-xl font-semibold whitespace-nowrap text-white">LIF Løb og Motion </span>
    <% end %>
    <%= if @current_user do %>
     <div id="dropdownDefault" data-dropdown-toggle="dropdown">
      <div class="grid grid-cols-2 gap-4">
        <%= img_tag Run.Uploader.Image.url({@current_user.avatar, @current_user}, :avatar),  class: "h-10 w-10 rounded-full"%> 
        <svg class="w-8 h-8 mt-1 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </div>
    </div>
    <!-- Dropdown menu -->
    <div id="dropdown" class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700">
        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefault">
          <%= if @current_user.admin do %>
            <li>
              <%= link gettext("Admin"), to: Routes.admin_path(@conn, :index), class: "block py-2 px-4 hover:bg-red-600 hover:text-white"  %>
            </li>
          <% end %>
					<li>
						<%= link gettext("Settings"), to: Routes.edit_member_path(@conn, :edit), class: "block py-2 px-4 hover:bg-red-600 hover:text-white"%>
						<%#= link gettext(""), to: Routes.user_settings_path(@conn, :edit), class: "block py-2 px-4 hover:bg-red-600 hover:text-white"%>
					</li>
          <li>
            <%= link gettext("Account"), to: Routes.show_member_path(@conn, :show), class: "block py-2 px-4 hover:bg-red-600 hover: text-white" %>
          </li>
					<li>
					  <%= link gettext("Log out"), to: Routes.user_session_path(@conn, :delete), method: :delete, class: "block py-2 px-4 hover:bg-red-600 hover:text-white" %>
					</li>
        </ul>
    </div>

    <% else %>
      <div class="static">
        <%= link gettext("Log in"), to: Routes.user_session_path(@conn, :new), class: "block py-2 hover:bg-red-600 text-white inline-block mr-3" %>
        <%= link gettext("Register"), to: Routes.new_member_path(@conn, :new), class: "btn btn-green pt-3 inline-block" %>
      </div>
    <% end %>
  </div>


</nav>

apps/run_web/lib/run_web/templates/layout/app.html.heex
  <%= case get_flash(@conn) do %>
    <% %{"info" => message} -> %>
    <div id="toast-success" class="fixed top-2 right-2 z-50 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white  shadow" role="alert">
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 ">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div class="ml-3 text-sm font-normal"><%= message %></div>
      <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900  focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 " data-dismiss-target="#toast-success" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
    </div>
  <% %{"error" => message} -> %>
  <div id="toast-danger" class="fixed top-2 right-2 z-50 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white  shadow" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 ">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </div>
    <div class="ml-3 text-sm font-normal"><%= message %></div>
    <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900  focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8" data-dismiss-target="#toast-danger" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
</div>
    <% %{} -> %>
      
  <% end %>
  
  <%= @inner_content %>

apps/run_web/lib/run_web/templates/layout/live.html.heex
<main class="relative">
  <%= if Enum.any?(@flash) do %>
    <div class="absolute top-0 right-4 z-40">
      <p class="flash flash-green" role="alert"
        phx-click="lv:clear-flash"
        phx-value-key="info"><%= live_flash(@flash, :info) %></p>
      <p class="alert alert-danger" role="alert"
        phx-click="lv:clear-flash"
        phx-value-key="error"><%= live_flash(@flash, :error) %></p>
    </div>
  <% end %>
  <%= @inner_content %>
</main>

apps/run_web/lib/run_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Run", suffix: " · Running Application" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script src="https://cdn.tiny.cloud/1/tzlwj2zjulv5ip3mavrlk4ljknmkqv7n8yyivelsou29j4eg/tinymce/6/tinymce.min.js"></script>

  </head>
  <body>
    <div class="page-wrap">
  
      <%= render "_navbar.html", assigns %>
      <%= render "_breadcrumbs.html", assigns %>
      <main class="mt-32">    
        <%= @inner_content %>
      </main>
     </div>
     <%= render "_footer.html", assigns %>
   

   	<script>
      //Javascript to toggle the menu
      document.getElementById('nav-toggle').onclick = function(){
      document.getElementById("nav-content").classList.toggle("hidden");
      }
    </script>
    <script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js"></script>
    
  </body>
</html>